version: '3.7'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: automaticschool
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123!
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:
  pgadmin:

networks:
  backend:
